/**
 * Commerce Growth OS - Mock Data Layer
 * Single Source of Truth (SSOT) for all mock data
 */

import type {
  Brand,
  Channel,
  Product,
  Customer,
  Order,
  Review,
  AdCampaign,
  Creative,
  Recommendation,
  KPISummary,
  CommerceMockData,
} from './types'

// =============================================================================
// Mock Data: Brands
// =============================================================================

const brands: Brand[] = [
  {
    id: 'brand-001',
    name: 'Glow Beauty',
    nameKr: '글로우 뷰티',
    domain: 'glowbeauty.kr',
    logo: '/images/demo/commerce/glow-beauty-logo.png',
    industry: 'Beauty & Cosmetics',
    currency: 'KRW',
    timezone: 'Asia/Seoul',
    createdAt: '2022-03-15',
  },
]

// =============================================================================
// Mock Data: Channels
// =============================================================================

const channels: Channel[] = [
  {
    id: 'ch-001',
    name: 'Shopify',
    type: 'ecommerce',
    platform: 'shopify',
    isConnected: true,
    lastSync: '2024-12-29T10:30:00Z',
    totalOrders: 8450,
    totalRevenue: 892500000,
    status: 'active',
  },
  {
    id: 'ch-002',
    name: 'Cafe24',
    type: 'ecommerce',
    platform: 'cafe24',
    isConnected: false,
    lastSync: null,
    totalOrders: 0,
    totalRevenue: 0,
    status: 'inactive',
  },
  {
    id: 'ch-003',
    name: 'Coupang',
    type: 'marketplace',
    platform: 'coupang',
    isConnected: true,
    lastSync: '2024-12-29T09:45:00Z',
    totalOrders: 3250,
    totalRevenue: 345000000,
    status: 'active',
  },
  {
    id: 'ch-004',
    name: 'Naver Smartstore',
    type: 'marketplace',
    platform: 'naver',
    isConnected: true,
    lastSync: '2024-12-29T10:00:00Z',
    totalOrders: 2180,
    totalRevenue: 215000000,
    status: 'active',
  },
  {
    id: 'ch-005',
    name: 'Instagram Shop',
    type: 'social',
    platform: 'instagram',
    isConnected: true,
    lastSync: '2024-12-28T18:00:00Z',
    totalOrders: 420,
    totalRevenue: 52000000,
    status: 'active',
  },
]

// =============================================================================
// Mock Data: Products
// =============================================================================

const products: Product[] = [
  {
    id: 'prod-001',
    name: 'Premium Skincare Set',
    nameKr: '프리미엄 스킨케어 세트',
    category: 'Skincare',
    categoryKr: '스킨케어',
    price: 98000,
    compareAtPrice: 120000,
    cost: 35000,
    margin: 64.3,
    inventory: 245,
    images: ['/images/demo/commerce/product-skincare-set.jpg'],
    totalSales: 1247,
    totalRevenue: 122206000,
    averageRating: 4.8,
    reviewCount: 892,
    isActive: true,
    createdAt: '2023-01-15',
  },
  {
    id: 'prod-002',
    name: 'Hydrating Toner',
    nameKr: '하이드레이팅 토너',
    category: 'Skincare',
    categoryKr: '스킨케어',
    price: 45000,
    cost: 12000,
    margin: 73.3,
    inventory: 580,
    images: ['/images/demo/commerce/product-toner.jpg'],
    totalSales: 2856,
    totalRevenue: 128520000,
    averageRating: 4.6,
    reviewCount: 1245,
    isActive: true,
    createdAt: '2023-02-20',
  },
  {
    id: 'prod-003',
    name: 'Anti-Aging Serum',
    nameKr: '안티에이징 세럼',
    category: 'Skincare',
    categoryKr: '스킨케어',
    price: 89000,
    compareAtPrice: 110000,
    cost: 28000,
    margin: 68.5,
    inventory: 320,
    images: ['/images/demo/commerce/product-serum.jpg'],
    totalSales: 1580,
    totalRevenue: 140620000,
    averageRating: 4.9,
    reviewCount: 678,
    isActive: true,
    createdAt: '2023-03-10',
  },
  {
    id: 'prod-004',
    name: 'Sunscreen SPF50+',
    nameKr: '선크림 SPF50+',
    category: 'Sun Care',
    categoryKr: '선케어',
    price: 32000,
    cost: 9500,
    margin: 70.3,
    inventory: 890,
    images: ['/images/demo/commerce/product-sunscreen.jpg'],
    totalSales: 4250,
    totalRevenue: 136000000,
    averageRating: 4.5,
    reviewCount: 2156,
    isActive: true,
    createdAt: '2023-04-05',
  },
  {
    id: 'prod-005',
    name: 'Cleansing Foam',
    nameKr: '클렌징 폼',
    category: 'Cleansing',
    categoryKr: '클렌징',
    price: 18000,
    cost: 4500,
    margin: 75.0,
    inventory: 1250,
    images: ['/images/demo/commerce/product-cleanser.jpg'],
    totalSales: 5680,
    totalRevenue: 102240000,
    averageRating: 4.4,
    reviewCount: 3421,
    isActive: true,
    createdAt: '2023-05-12',
  },
]

// =============================================================================
// Mock Data: Customers (with RFM)
// =============================================================================

const customers: Customer[] = [
  {
    id: 'cust-001',
    name: '김민지',
    email: 'minji.k@email.com',
    phone: '010-1234-5678',
    rfm: {
      recency: 2,
      frequency: 15,
      monetary: 1850000,
      score: 'VIP',
      lastCalculated: '2024-12-29',
    },
    totalOrders: 15,
    totalSpent: 1850000,
    averageOrderValue: 123333,
    ltv: 2775000,
    firstOrderDate: '2023-06-15',
    lastOrderDate: '2024-12-27',
    preferredChannel: 'Shopify',
    tags: ['VIP', 'Beauty Lover', 'High LTV'],
    isSubscribed: true,
    createdAt: '2023-06-15',
  },
  {
    id: 'cust-002',
    name: '이서윤',
    email: 'seoyun.l@email.com',
    phone: '010-2345-6789',
    rfm: {
      recency: 5,
      frequency: 8,
      monetary: 890000,
      score: 'Loyal',
      lastCalculated: '2024-12-29',
    },
    totalOrders: 8,
    totalSpent: 890000,
    averageOrderValue: 111250,
    ltv: 1120000,
    firstOrderDate: '2023-09-22',
    lastOrderDate: '2024-12-24',
    preferredChannel: 'Shopify',
    tags: ['Loyal', 'Skincare Focus'],
    isSubscribed: true,
    createdAt: '2023-09-22',
  },
  {
    id: 'cust-003',
    name: '박지원',
    email: 'jiwon.p@email.com',
    phone: '010-3456-7890',
    rfm: {
      recency: 8,
      frequency: 3,
      monetary: 185000,
      score: 'Regular',
      lastCalculated: '2024-12-29',
    },
    totalOrders: 3,
    totalSpent: 185000,
    averageOrderValue: 61667,
    ltv: 280000,
    firstOrderDate: '2024-11-05',
    lastOrderDate: '2024-12-21',
    preferredChannel: 'Naver Smartstore',
    tags: ['New Customer'],
    isSubscribed: true,
    createdAt: '2024-11-05',
  },
  {
    id: 'cust-004',
    name: '최유나',
    email: 'yuna.c@email.com',
    phone: '010-4567-8901',
    rfm: {
      recency: 3,
      frequency: 28,
      monetary: 3850000,
      score: 'VIP',
      lastCalculated: '2024-12-29',
    },
    totalOrders: 28,
    totalSpent: 3850000,
    averageOrderValue: 137500,
    ltv: 5780000,
    firstOrderDate: '2022-03-10',
    lastOrderDate: '2024-12-26',
    preferredChannel: 'Shopify',
    tags: ['VIP', 'Brand Ambassador', 'Top Spender'],
    isSubscribed: true,
    createdAt: '2022-03-10',
  },
  {
    id: 'cust-005',
    name: '정하은',
    email: 'haeun.j@email.com',
    phone: '010-5678-9012',
    rfm: {
      recency: 12,
      frequency: 6,
      monetary: 520000,
      score: 'Regular',
      lastCalculated: '2024-12-29',
    },
    totalOrders: 6,
    totalSpent: 520000,
    averageOrderValue: 86667,
    ltv: 680000,
    firstOrderDate: '2024-01-18',
    lastOrderDate: '2024-12-17',
    preferredChannel: 'Coupang',
    tags: ['Regular'],
    isSubscribed: false,
    createdAt: '2024-01-18',
  },
  {
    id: 'cust-006',
    name: '강지수',
    email: 'jisoo.k@email.com',
    phone: '010-6789-0123',
    rfm: {
      recency: 45,
      frequency: 2,
      monetary: 95000,
      score: 'AtRisk',
      lastCalculated: '2024-12-29',
    },
    totalOrders: 2,
    totalSpent: 95000,
    averageOrderValue: 47500,
    ltv: 95000,
    firstOrderDate: '2024-08-15',
    lastOrderDate: '2024-11-14',
    preferredChannel: 'Instagram Shop',
    tags: ['At Risk', 'Needs Reactivation'],
    isSubscribed: true,
    createdAt: '2024-08-15',
  },
  {
    id: 'cust-007',
    name: '윤서아',
    email: 'seoa.y@email.com',
    phone: '010-7890-1234',
    rfm: {
      recency: 4,
      frequency: 18,
      monetary: 2150000,
      score: 'VIP',
      lastCalculated: '2024-12-29',
    },
    totalOrders: 18,
    totalSpent: 2150000,
    averageOrderValue: 119444,
    ltv: 3225000,
    firstOrderDate: '2023-02-28',
    lastOrderDate: '2024-12-25',
    preferredChannel: 'Shopify',
    tags: ['VIP', 'Serum Enthusiast'],
    isSubscribed: true,
    createdAt: '2023-02-28',
  },
  {
    id: 'cust-008',
    name: '임수빈',
    email: 'subin.l@email.com',
    phone: '010-8901-2345',
    rfm: {
      recency: 18,
      frequency: 4,
      monetary: 320000,
      score: 'Regular',
      lastCalculated: '2024-12-29',
    },
    totalOrders: 4,
    totalSpent: 320000,
    averageOrderValue: 80000,
    ltv: 420000,
    firstOrderDate: '2024-05-12',
    lastOrderDate: '2024-12-11',
    preferredChannel: 'Naver Smartstore',
    tags: ['Regular', 'Price Sensitive'],
    isSubscribed: true,
    createdAt: '2024-05-12',
  },
  {
    id: 'cust-009',
    name: '한예진',
    email: 'yejin.h@email.com',
    phone: '010-9012-3456',
    rfm: {
      recency: 95,
      frequency: 2,
      monetary: 98000,
      score: 'Dormant',
      lastCalculated: '2024-12-29',
    },
    totalOrders: 2,
    totalSpent: 98000,
    averageOrderValue: 49000,
    ltv: 98000,
    firstOrderDate: '2024-03-20',
    lastOrderDate: '2024-09-25',
    preferredChannel: 'Coupang',
    tags: ['Dormant', 'Win-back Target'],
    isSubscribed: false,
    createdAt: '2024-03-20',
  },
  {
    id: 'cust-010',
    name: '송다연',
    email: 'dayeon.s@email.com',
    phone: '010-0123-4567',
    rfm: {
      recency: 120,
      frequency: 1,
      monetary: 52000,
      score: 'Dormant',
      lastCalculated: '2024-12-29',
    },
    totalOrders: 1,
    totalSpent: 52000,
    averageOrderValue: 52000,
    ltv: 52000,
    firstOrderDate: '2024-07-28',
    lastOrderDate: '2024-07-28',
    preferredChannel: 'Instagram Shop',
    tags: ['Dormant', 'One-time Buyer'],
    isSubscribed: false,
    createdAt: '2024-07-28',
  },
]

// =============================================================================
// Mock Data: Orders
// =============================================================================

const orders: Order[] = [
  {
    id: 'ord-001',
    orderNumber: 'ORD-2024-1847',
    customerId: 'cust-001',
    customerName: '김민지',
    customerEmail: 'minji.k@email.com',
    channelId: 'ch-001',
    channelName: 'Shopify',
    items: [
      { productId: 'prod-001', productName: '프리미엄 스킨케어 세트', quantity: 1, unitPrice: 98000, totalPrice: 98000 },
    ],
    subtotal: 98000,
    discount: 9800,
    shipping: 0,
    tax: 0,
    total: 88200,
    status: 'delivered',
    paymentMethod: 'Credit Card',
    shippingAddress: '서울시 강남구 테헤란로 123',
    isRepeatCustomer: true,
    createdAt: '2024-12-27T14:30:00Z',
    updatedAt: '2024-12-29T10:00:00Z',
  },
  {
    id: 'ord-002',
    orderNumber: 'ORD-2024-1846',
    customerId: 'cust-002',
    customerName: '이서윤',
    customerEmail: 'seoyun.l@email.com',
    channelId: 'ch-001',
    channelName: 'Shopify',
    items: [
      { productId: 'prod-002', productName: '하이드레이팅 토너', quantity: 2, unitPrice: 45000, totalPrice: 90000 },
      { productId: 'prod-003', productName: '안티에이징 세럼', quantity: 1, unitPrice: 89000, totalPrice: 89000 },
    ],
    subtotal: 179000,
    discount: 17900,
    shipping: 0,
    tax: 0,
    total: 161100,
    status: 'shipped',
    paymentMethod: 'Kakao Pay',
    shippingAddress: '서울시 마포구 와우산로 456',
    isRepeatCustomer: true,
    createdAt: '2024-12-28T09:15:00Z',
    updatedAt: '2024-12-29T08:00:00Z',
  },
  {
    id: 'ord-003',
    orderNumber: 'ORD-2024-1845',
    customerId: 'cust-003',
    customerName: '박지원',
    customerEmail: 'jiwon.p@email.com',
    channelId: 'ch-004',
    channelName: 'Naver Smartstore',
    items: [
      { productId: 'prod-004', productName: '선크림 SPF50+', quantity: 1, unitPrice: 32000, totalPrice: 32000 },
      { productId: 'prod-005', productName: '클렌징 폼', quantity: 1, unitPrice: 18000, totalPrice: 18000 },
    ],
    subtotal: 50000,
    discount: 5000,
    shipping: 3000,
    tax: 0,
    total: 48000,
    status: 'processing',
    paymentMethod: 'Naver Pay',
    shippingAddress: '경기도 성남시 분당구 판교로 789',
    isRepeatCustomer: true,
    createdAt: '2024-12-28T16:45:00Z',
    updatedAt: '2024-12-28T16:45:00Z',
  },
  {
    id: 'ord-004',
    orderNumber: 'ORD-2024-1844',
    customerId: 'cust-004',
    customerName: '최유나',
    customerEmail: 'yuna.c@email.com',
    channelId: 'ch-001',
    channelName: 'Shopify',
    items: [
      { productId: 'prod-001', productName: '프리미엄 스킨케어 세트', quantity: 2, unitPrice: 98000, totalPrice: 196000 },
      { productId: 'prod-003', productName: '안티에이징 세럼', quantity: 1, unitPrice: 89000, totalPrice: 89000 },
    ],
    subtotal: 285000,
    discount: 42750,
    shipping: 0,
    tax: 0,
    total: 242250,
    status: 'delivered',
    paymentMethod: 'Credit Card',
    shippingAddress: '서울시 서초구 반포대로 321',
    isRepeatCustomer: true,
    createdAt: '2024-12-26T11:20:00Z',
    updatedAt: '2024-12-28T14:00:00Z',
  },
  {
    id: 'ord-005',
    orderNumber: 'ORD-2024-1843',
    customerId: 'cust-005',
    customerName: '정하은',
    customerEmail: 'haeun.j@email.com',
    channelId: 'ch-003',
    channelName: 'Coupang',
    items: [
      { productId: 'prod-002', productName: '하이드레이팅 토너', quantity: 1, unitPrice: 45000, totalPrice: 45000 },
      { productId: 'prod-005', productName: '클렌징 폼', quantity: 2, unitPrice: 18000, totalPrice: 36000 },
    ],
    subtotal: 81000,
    discount: 8100,
    shipping: 0,
    tax: 0,
    total: 72900,
    status: 'delivered',
    paymentMethod: 'Coupang Pay',
    shippingAddress: '인천시 남동구 구월동 654',
    isRepeatCustomer: true,
    createdAt: '2024-12-25T13:00:00Z',
    updatedAt: '2024-12-27T16:00:00Z',
  },
]

// =============================================================================
// Mock Data: Reviews
// =============================================================================

const reviews: Review[] = [
  {
    id: 'rev-001',
    productId: 'prod-001',
    productName: '프리미엄 스킨케어 세트',
    customerId: 'cust-001',
    customerName: '김민지',
    orderId: 'ord-001',
    rating: 5,
    title: '최고의 스킨케어 세트!',
    content: '피부가 정말 촉촉해지고 환해졌어요. 세럼이 특히 마음에 들어요. 재구매 의사 100%입니다.',
    images: ['/images/demo/commerce/review-001.jpg'],
    isVerified: true,
    helpfulCount: 45,
    reply: {
      content: '소중한 리뷰 감사합니다! 앞으로도 만족스러운 제품으로 보답하겠습니다.',
      repliedAt: '2024-12-28T10:00:00Z',
    },
    createdAt: '2024-12-27T18:00:00Z',
  },
  {
    id: 'rev-002',
    productId: 'prod-002',
    productName: '하이드레이팅 토너',
    customerId: 'cust-002',
    customerName: '이서윤',
    orderId: 'ord-002',
    rating: 4,
    title: '좋은 토너예요',
    content: '수분감이 오래 유지되고 피부에 자극이 없어서 좋아요. 향이 조금 강한 편이에요.',
    isVerified: true,
    helpfulCount: 28,
    createdAt: '2024-12-26T14:30:00Z',
  },
  {
    id: 'rev-003',
    productId: 'prod-003',
    productName: '안티에이징 세럼',
    customerId: 'cust-004',
    customerName: '최유나',
    orderId: 'ord-004',
    rating: 5,
    title: '피부결이 달라졌어요',
    content: '한 달 사용했는데 잔주름이 눈에 띄게 줄었어요. 가격대비 효과가 정말 좋습니다.',
    images: ['/images/demo/commerce/review-003-1.jpg', '/images/demo/commerce/review-003-2.jpg'],
    isVerified: true,
    helpfulCount: 89,
    reply: {
      content: '변화를 느끼셨다니 정말 기쁩니다! 꾸준한 사용으로 더 좋은 결과 있으시길 바랍니다.',
      repliedAt: '2024-12-27T09:00:00Z',
    },
    createdAt: '2024-12-26T20:15:00Z',
  },
  {
    id: 'rev-004',
    productId: 'prod-004',
    productName: '선크림 SPF50+',
    customerId: 'cust-005',
    customerName: '정하은',
    orderId: 'ord-005',
    rating: 4,
    title: '백탁 없이 발림성 좋아요',
    content: '다른 선크림에 비해 백탁이 거의 없고 가볍게 발려서 좋아요. 지속력도 괜찮습니다.',
    isVerified: true,
    helpfulCount: 34,
    createdAt: '2024-12-25T11:00:00Z',
  },
  {
    id: 'rev-005',
    productId: 'prod-005',
    productName: '클렌징 폼',
    customerId: 'cust-007',
    customerName: '윤서아',
    orderId: 'ord-005',
    rating: 5,
    title: '순하고 깔끔해요',
    content: '민감한 피부인데 전혀 자극 없이 깔끔하게 세안돼요. 거품도 풍성하고 좋아요.',
    isVerified: true,
    helpfulCount: 52,
    createdAt: '2024-12-24T16:45:00Z',
  },
]

// =============================================================================
// Mock Data: Ad Campaigns
// =============================================================================

const adCampaigns: AdCampaign[] = [
  {
    id: 'camp-001',
    name: 'Winter Sale 2024',
    platform: 'meta',
    status: 'active',
    objective: 'conversion',
    budget: 5000000,
    spent: 3250000,
    impressions: 1250000,
    clicks: 42500,
    conversions: 1280,
    revenue: 13650000,
    roas: 4.2,
    cpa: 2539,
    ctr: 3.4,
    cvr: 3.01,
    startDate: '2024-12-01',
    endDate: '2024-12-31',
    creatives: ['cre-001', 'cre-002'],
  },
  {
    id: 'camp-002',
    name: 'New Year Collection',
    platform: 'google',
    status: 'active',
    objective: 'conversion',
    budget: 3000000,
    spent: 1850000,
    impressions: 890000,
    clicks: 28700,
    conversions: 720,
    revenue: 7030000,
    roas: 3.8,
    cpa: 2569,
    ctr: 3.22,
    cvr: 2.51,
    startDate: '2024-12-15',
    endDate: '2025-01-15',
    creatives: ['cre-003'],
  },
  {
    id: 'camp-003',
    name: 'Skincare Routine',
    platform: 'meta',
    status: 'paused',
    objective: 'awareness',
    budget: 2000000,
    spent: 2000000,
    impressions: 620000,
    clicks: 18600,
    conversions: 485,
    revenue: 5800000,
    roas: 2.9,
    cpa: 4124,
    ctr: 3.0,
    cvr: 2.61,
    startDate: '2024-11-01',
    endDate: '2024-11-30',
    creatives: ['cre-004', 'cre-005'],
  },
  {
    id: 'camp-004',
    name: 'Brand Awareness',
    platform: 'tiktok',
    status: 'active',
    objective: 'awareness',
    budget: 1500000,
    spent: 680000,
    impressions: 2100000,
    clicks: 52500,
    conversions: 320,
    revenue: 1428000,
    roas: 2.1,
    cpa: 2125,
    ctr: 2.5,
    cvr: 0.61,
    startDate: '2024-12-10',
    creatives: ['cre-006'],
  },
  {
    id: 'camp-005',
    name: 'Retargeting Cart',
    platform: 'google',
    status: 'active',
    objective: 'conversion',
    budget: 1000000,
    spent: 520000,
    impressions: 180000,
    clicks: 8640,
    conversions: 412,
    revenue: 3536000,
    roas: 6.8,
    cpa: 1262,
    ctr: 4.8,
    cvr: 4.77,
    startDate: '2024-12-01',
    creatives: ['cre-007'],
  },
]

// =============================================================================
// Mock Data: Creatives
// =============================================================================

const creatives: Creative[] = [
  {
    id: 'cre-001',
    campaignId: 'camp-001',
    name: 'Winter Sale - Hero Image',
    type: 'image',
    format: '1080x1080',
    headline: '겨울 세일 최대 50% OFF',
    description: '지금 바로 만나보세요',
    callToAction: 'Shop Now',
    mediaUrl: '/images/demo/commerce/creative-001.jpg',
    thumbnailUrl: '/images/demo/commerce/creative-001-thumb.jpg',
    impressions: 750000,
    clicks: 28500,
    conversions: 820,
    ctr: 3.8,
    isActive: true,
    createdAt: '2024-11-28',
  },
  {
    id: 'cre-002',
    campaignId: 'camp-001',
    name: 'Winter Sale - Carousel',
    type: 'carousel',
    format: '1080x1080',
    headline: '베스트셀러 모음',
    description: '고객이 사랑한 제품들',
    callToAction: 'Learn More',
    mediaUrl: '/images/demo/commerce/creative-002.jpg',
    impressions: 500000,
    clicks: 14000,
    conversions: 460,
    ctr: 2.8,
    isActive: true,
    createdAt: '2024-11-28',
  },
  {
    id: 'cre-003',
    campaignId: 'camp-002',
    name: 'New Year - Search Ad',
    type: 'text',
    format: 'text',
    headline: '새해 스킨케어 루틴 시작하기',
    description: '프리미엄 스킨케어 세트로 완벽한 피부 관리',
    callToAction: 'Buy Now',
    mediaUrl: '',
    impressions: 890000,
    clicks: 28700,
    conversions: 720,
    ctr: 3.22,
    isActive: true,
    createdAt: '2024-12-14',
  },
  {
    id: 'cre-004',
    campaignId: 'camp-003',
    name: 'Skincare Tutorial',
    type: 'video',
    format: '1920x1080',
    headline: '3분 스킨케어 루틴',
    description: '전문가가 알려주는 올바른 스킨케어 순서',
    callToAction: 'Watch Now',
    mediaUrl: '/images/demo/commerce/creative-004.mp4',
    thumbnailUrl: '/images/demo/commerce/creative-004-thumb.jpg',
    impressions: 420000,
    clicks: 12600,
    conversions: 285,
    ctr: 3.0,
    isActive: false,
    createdAt: '2024-10-28',
  },
  {
    id: 'cre-005',
    campaignId: 'camp-003',
    name: 'Product Showcase',
    type: 'image',
    format: '1080x1920',
    headline: '안티에이징 세럼',
    description: '피부 탄력의 비밀',
    callToAction: 'Shop Now',
    mediaUrl: '/images/demo/commerce/creative-005.jpg',
    impressions: 200000,
    clicks: 6000,
    conversions: 200,
    ctr: 3.0,
    isActive: false,
    createdAt: '2024-10-28',
  },
  {
    id: 'cre-006',
    campaignId: 'camp-004',
    name: 'TikTok Trend',
    type: 'video',
    format: '1080x1920',
    headline: '#GlowUpChallenge',
    description: '글로우 뷰티와 함께 피부 변화',
    callToAction: 'Join Challenge',
    mediaUrl: '/images/demo/commerce/creative-006.mp4',
    thumbnailUrl: '/images/demo/commerce/creative-006-thumb.jpg',
    impressions: 2100000,
    clicks: 52500,
    conversions: 320,
    ctr: 2.5,
    isActive: true,
    createdAt: '2024-12-09',
  },
  {
    id: 'cre-007',
    campaignId: 'camp-005',
    name: 'Cart Abandonment',
    type: 'image',
    format: '1200x628',
    headline: '장바구니에 담긴 상품이 기다리고 있어요',
    description: '지금 구매하면 10% 추가 할인',
    callToAction: 'Complete Purchase',
    mediaUrl: '/images/demo/commerce/creative-007.jpg',
    impressions: 180000,
    clicks: 8640,
    conversions: 412,
    ctr: 4.8,
    isActive: true,
    createdAt: '2024-11-30',
  },
]

// =============================================================================
// Mock Data: Recommendations
// =============================================================================

const recommendations: Recommendation[] = [
  {
    id: 'rec-001',
    type: 'retention',
    priority: 'high',
    title: 'VIP Customer Retention Campaign',
    titleKr: 'VIP 고객 유지 캠페인',
    description: 'Send exclusive offers to 245 VIP customers who haven\'t purchased in 14+ days',
    descriptionKr: '14일 이상 구매하지 않은 245명의 VIP 고객에게 전용 혜택 발송',
    targetSegment: 'VIP',
    targetCustomerCount: 245,
    estimatedRevenue: 24500000,
    estimatedROI: 380,
    actionLabel: 'Create Campaign',
    actionLabelKr: '캠페인 생성',
    actionUrl: '/demo/commerce/crm',
    isNew: true,
    createdAt: '2024-12-29',
  },
  {
    id: 'rec-002',
    type: 'reactivation',
    priority: 'high',
    title: 'Win-back Dormant Customers',
    titleKr: '휴면 고객 재활성화',
    description: 'Re-engage 1,955 dormant customers with personalized comeback offers',
    descriptionKr: '개인화된 복귀 혜택으로 1,955명의 휴면 고객 재활성화',
    targetSegment: 'Dormant',
    targetCustomerCount: 1955,
    estimatedRevenue: 48750000,
    estimatedROI: 250,
    actionLabel: 'View Segment',
    actionLabelKr: '세그먼트 보기',
    actionUrl: '/demo/commerce/customers',
    isNew: true,
    createdAt: '2024-12-29',
  },
  {
    id: 'rec-003',
    type: 'upsell',
    priority: 'medium',
    title: 'Bundle Upsell Opportunity',
    titleKr: '번들 업셀 기회',
    description: 'Promote Premium Skincare Set to Toner buyers - 68% conversion potential',
    descriptionKr: '토너 구매자에게 프리미엄 스킨케어 세트 프로모션 - 68% 전환 가능성',
    estimatedRevenue: 15200000,
    estimatedROI: 420,
    actionLabel: 'Create Offer',
    actionLabelKr: '오퍼 생성',
    actionUrl: '/demo/commerce/crm',
    isNew: false,
    createdAt: '2024-12-28',
  },
  {
    id: 'rec-004',
    type: 'cross-sell',
    priority: 'medium',
    title: 'Cross-sell Sunscreen to Serum Buyers',
    titleKr: '세럼 구매자에게 선크림 크로스셀',
    description: 'Recommend SPF50+ to customers who bought Anti-Aging Serum',
    descriptionKr: '안티에이징 세럼 구매자에게 SPF50+ 추천',
    estimatedRevenue: 8960000,
    estimatedROI: 320,
    actionLabel: 'Set Up Cross-sell',
    actionLabelKr: '크로스셀 설정',
    actionUrl: '/demo/commerce/crm',
    isNew: false,
    createdAt: '2024-12-27',
  },
  {
    id: 'rec-005',
    type: 'acquisition',
    priority: 'low',
    title: 'Lookalike Audience Expansion',
    titleKr: '유사 오디언스 확장',
    description: 'Create lookalike audience from VIP customers for Meta Ads',
    descriptionKr: 'VIP 고객 기반 Meta Ads 유사 오디언스 생성',
    targetCustomerCount: 50000,
    estimatedRevenue: 125000000,
    estimatedROI: 280,
    actionLabel: 'Create Audience',
    actionLabelKr: '오디언스 생성',
    actionUrl: '/demo/commerce/ads',
    isNew: false,
    createdAt: '2024-12-26',
  },
]

// =============================================================================
// Mock Data: KPI Summary
// =============================================================================

const kpiSummary: KPISummary = {
  // 필수 5개 필드
  totalRevenue: 1504500000,
  grossMargin: 68.5,
  AOV: 87400,
  repeatRevenuePct: 72.3,
  blendedROAS: 3.85,

  // 추가 메트릭
  totalOrders: 17220,
  totalCustomers: 12453,
  newCustomers: 3421,
  returningCustomers: 9032,
  totalAdSpend: 8300000,
  totalConversions: 3217,

  // 기간
  period: {
    start: '2024-12-01',
    end: '2024-12-29',
    label: '이번 달',
  },
  comparison: {
    revenueChange: 12.5,
    ordersChange: 8.3,
    aovChange: 3.8,
    roasChange: 5.2,
  },
}

// =============================================================================
// Getter Functions
// =============================================================================

/**
 * Get all mock data as a single object
 */
export const getMockData = (): CommerceMockData => ({
  brands,
  channels,
  products,
  customers,
  orders,
  reviews,
  adCampaigns,
  creatives,
  recommendations,
  kpiSummary,
})

// Individual getters
export const getBrands = (): Brand[] => brands
export const getChannels = (): Channel[] => channels
export const getProducts = (): Product[] => products
export const getCustomers = (): Customer[] => customers
export const getOrders = (): Order[] => orders
export const getReviews = (): Review[] => reviews
export const getAdCampaigns = (): AdCampaign[] => adCampaigns
export const getCreatives = (): Creative[] => creatives
export const getRecommendations = (): Recommendation[] => recommendations
export const getKPISummary = (): KPISummary => kpiSummary

// Filtered getters
export const getCustomersBySegment = (segment: string): Customer[] =>
  customers.filter((c) => c.rfm.score === segment)

export const getOrdersByStatus = (status: string): Order[] =>
  orders.filter((o) => o.status === status)

export const getActiveAdCampaigns = (): AdCampaign[] =>
  adCampaigns.filter((c) => c.status === 'active')

export const getHighPriorityRecommendations = (): Recommendation[] =>
  recommendations.filter((r) => r.priority === 'high')

export const getProductById = (id: string): Product | undefined =>
  products.find((p) => p.id === id)

export const getCustomerById = (id: string): Customer | undefined =>
  customers.find((c) => c.id === id)

export const getOrderById = (id: string): Order | undefined =>
  orders.find((o) => o.id === id)
